### ISSUE TITLE
Modal is not shown entirely on a page with blasorize animate tags added

### ISSUE THREAD

**Issue by marcdieters** [Megabit/Blazorise#3238]
**Describe the bug**
When a small table is shown on a page with Blasorize Animation enabled, and a modal is opened it's cut off at the bottom of the table. This does not happen when the page is shown without the animation
![image](https://user-images.githubusercontent.com/24914093/146527328-d51e6f96-f72b-414b-a34d-8b1ecd5ff87c.png)

**To Reproduce**
To Reproduce
- Add animation tag to a page
- Create a basic blasorize modal
```
<Modal @ref="modalRef" ShowBackdrop="false">
    <ModalContent Size="ModalSize.Large" Centered="false">
        <ModalHeader>
            <ModalTitle>
                <h5 class="modal-title" id="titleLabel">@Name Options</h5>
            </ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <p>
            </p>
        </ModalBody>
        <ModalFooter>
            <a class="btn btn-outline-primary" @onclick="@Close">Close</a>
        </ModalFooter>
    </ModalContent>
</Modal>
```

**Expected behavior**
Expected behaviour is that the modal shows entirely on a page with <animate> tags added.

**Comment by David-Moreira** [comment]
Currently investigating this, Animation needs to be defined. 

Can confirm there's some kind of css setting, overflow, size or whatever limitation that's making it so the modal will not show up if inside the `Animate` component.
We'll let you know when we have more info.

```
<Animate Animation="Animations.ZoomIn" Duration="TimeSpan.FromSeconds(0.5)" >
    <Label>Yo</Label>
    <Button Clicked="async () => await modalRef.Show()">Open Modal</Button>
    <Button Clicked="async () => await modalRef2.Show()">Open Modal 2</Button>
    <Modal @ref="modalRef" ShowBackdrop="false">
        <ModalContent Size="ModalSize.Large" Centered="false">
            <ModalHeader>
                <ModalTitle>
                    <h5 class="modal-title" id="titleLabel">@Name Options</h5>
                </ModalTitle>
                <CloseButton />
            </ModalHeader>
            <ModalBody>
                <p>
                </p>
            </ModalBody>
            <ModalFooter>
                <a class="btn btn-outline-primary" @onclick="@Close">Close</a>
            </ModalFooter>
        </ModalContent>
    </Modal>
</Animate>

<Modal @ref="modalRef2" ShowBackdrop="false">
    <ModalContent Size="ModalSize.Large" Centered="false">
        <ModalHeader>
            <ModalTitle>
                <h5 class="modal-title" id="titleLabel">@Name Options</h5>
            </ModalTitle>
            <CloseButton />
        </ModalHeader>
        <ModalBody>
            <p>
            </p>
        </ModalBody>
        <ModalFooter>
            <a class="btn btn-outline-primary" @onclick="@Close">Close</a>
        </ModalFooter>
    </ModalContent>
</Modal>
@code {
    Modal modalRef;
    Modal modalRef2;
    private string Name;

    private void Close()
    {
        return;
    }
}
```

**Comment by David-Moreira** [comment]
Hello,
Has to do with the animation library (aos) setting custom css with the animations that make it so the modal does not show properly.
![image](https://user-images.githubusercontent.com/22283161/147010335-d9588583-413d-4f84-b138-682651af8834.png)

@stsrki 
Any suggestions?
- display:contents seem to work nice here. Should we just apply it to the animation div?
- somehow remove the custom css after the animation has occurred?

**Comment by stsrki** [comment]
I don't think we need to do anything here. The problem is in the AOS library and if would do anything we would have to adjust native Bootstrap/Bulma/AntDesign modal styles. While doable I would like to not mess it.

And after all. We have already implemented fully native animations in the v1.0 branch with native support. So it could mess things even more.

**Comment by David-Moreira** [comment]
@marcdieters can you try applying 
display:contents
to your animate component div and see if everything works as you'd like?

**Comment by marcdieters** [comment]
@David-Moreira That doesn't help, I added it as following:
![image](https://user-images.githubusercontent.com/24914093/147205104-6cc5715e-5427-4f61-89c9-581f3e3370e8.png)

But the modal is still not showing entirely

**Comment by David-Moreira** [comment]
It should be added on the Animate component itself, that's the culprit div. :) 
Let us know how it goes!

**Comment by marcdieters** [comment]
@David-Moreira The modal now shows properly but the animation doesn't work anymore.

**Comment by David-Moreira** [comment]
Ah... so it messes the animation... :( 
Can I ask that you report the problem on https://github.com/michalsnik/aos which is the underlying library that component uses?
Basically tell them that the Animate changes the div it is used on, in a way it won't work well with other nested components, like with for example bootstrap modals, due to the applied css, like transform.

Now I have to ask... @marcdieters do you really need the modal to be inside the `Animate` component? What's the benefit of nesting it inside the `Animate` component? Is that a requirement of yours? Can't you just move it outside?

**Comment by marcdieters** [comment]
Well, the table being shown is animated. Each row has an options button at the end, which shows this modal.
The modal itself isn't in the animate component, it's a seperate razor component.

But it is called from the table shown in the animate component.

I'll post the issue in the AOS repo.

Thanks for the help !

**Comment by David-Moreira** [comment]
>The modal itself isn't in the animate component, it's a seperate razor component.

>But it is called from the table shown in the animate component.

Then my guess is you can move it outside and there's no real issue here. Modals are pretty much always placed under the body tag as you usually don't need to nest them anywhere else, since they usually just have fixed positions on the screen and only need to sit in the html hidden.

**Comment by David-Moreira** [comment]
@marcdieters were you able to figure this one out?

**Comment by marcdieters** [comment]
> @marcdieters were you able to figure this one out?

Hallo, I didn't get any reply from the AOS guys so I decide to ditch this completely. I use regular css classes now which works fine.

I can't use you solution since the modal is called from several pages, not just one.

**Comment by stsrki** [comment]
Closing the ticket now.
